### ISSUE TITLE
[CI] Build and Release workflow to produce binary artifacts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/kubeopenapi-jsonschema#2]
#### Current Behavior
A build and release workflow is missing for this repo.

#### Desired Behavior
Meshery Adapters that need to use this utility will ideally reference https://github.com/layer5io/kubeopenapi-jsonschema/releases/latest for a copy of the latest binaries for this utility.

#### Implementation
1. Create a workflow that triggers on a Release event.
1. Build the utilities binaries (minimally for Linux arch, with Win and Mac being nice-to-have).
1. Capture and persist the binaries in as Release artifacts.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by sayantan1413** [comment]
Hey @leecalcote I want ot try this out. But I could not assign myself as I do not have the permission I guess.

**Comment by leecalcote** [comment]
Weird. Let's get you that permission...

**Comment by leecalcote** [comment]
Updated...

**Comment by iamsdas** [comment]
Is anyone working on this issue right now? If not, can I try my hands on it?

**Comment by warunicorn19** [comment]
@iamsdas I don't think anyone is working on this, it would be great if you took a look.
